// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function divider(dataContent) {
  return React.cloneElement(React.createElement("li", {
                  className: "divider"
                }), {
              "data-content": dataContent
            });
}

exports.divider = divider;
/* react Not a pure module */
