// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Nav$ReactTemplate = require("./components/Nav.bs.js");
var Footer$ReactTemplate = require("./components/Footer.bs.js");
var BallotBar$ReactTemplate = require("./components/BallotBar.bs.js");
var PhaseView$ReactTemplate = require("./components/PhaseView.bs.js");
var BallotDetails$ReactTemplate = require("./components/BallotDetails.bs.js");

var component = ReasonReact.statelessComponent("Root");

function str(str_) {
  return str_;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Nav$ReactTemplate.make(/* array */[])), React.createElement("section", {
                              className: "section"
                            }, React.createElement("div", {
                                  className: "container"
                                }, React.createElement("div", {
                                      className: "tile is-ancestor"
                                    }, React.createElement("div", {
                                          className: "tile is-parent"
                                        }, React.createElement("div", {
                                              className: "tile is-child"
                                            }, ReasonReact.element(/* None */0, /* None */0, BallotDetails$ReactTemplate.make(/* array */[])), React.createElement("hr", undefined), ReasonReact.element(/* None */0, /* None */0, PhaseView$ReactTemplate.make(/* array */[])))), React.createElement("div", {
                                          className: "tile is-parent is-3"
                                        }, React.createElement("div", {
                                              className: "tile is-child"
                                            }, ReasonReact.element(/* None */0, /* None */0, BallotBar$ReactTemplate.make(/* array */[]))))))), ReasonReact.element(/* None */0, /* None */0, Footer$ReactTemplate.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
