// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SideBar$ReactTemplate = require("./components/SideBar.bs.js");
var BallotBar$ReactTemplate = require("./components/BallotBar.bs.js");

var component = ReasonReact.statelessComponent("Root");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "wrapper"
                        }, React.createElement("div", {
                              className: "side-bar-wrapper"
                            }, ReasonReact.element(/* None */0, /* None */0, SideBar$ReactTemplate.make(/* array */[]))), React.createElement("div", {
                              className: "content-wrapper"
                            }, "content"), React.createElement("div", {
                              className: "ballot-bar-wrapper"
                            }, ReasonReact.element(/* None */0, /* None */0, BallotBar$ReactTemplate.make(/* array */[]))), React.createElement("div", {
                              className: "cmd-wrapper"
                            }, "cmd"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
