// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BallotCard");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "ballot-card"
                        }, React.createElement("div", {
                              className: "tile tile-centered"
                            }, React.createElement("div", {
                                  className: "tile-icon"
                                }, React.cloneElement(React.createElement("div", {
                                          className: "phase bg-secondary rounded tooltip tooltip-right float-right h3"
                                        }), {
                                      "data-tooltip": "Lorem Ispum"
                                    }, "C")), React.createElement("div", {
                                  className: "tile-content"
                                }, React.createElement("div", {
                                      className: "tile-title"
                                    }, "General Secretary Elections"), React.createElement("div", {
                                      className: "tile-subtitle text-gray"
                                    }, "GS-2015")), React.createElement("div", {
                                  className: "tile-action"
                                }, React.createElement("button", {
                                      className: "btn"
                                    }, "Open"))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
