// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BallotBar");

function str(str_) {
  return str_;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          className: "panel"
                        }, React.createElement("p", {
                              className: "panel-heading"
                            }, "Meine Ballots"), React.createElement("div", {
                              className: "panel-block"
                            }, React.createElement("p", {
                                  className: "control has-icons-left"
                                }, React.createElement("input", {
                                      className: "input is-small",
                                      placeholder: "search",
                                      type: "text"
                                    }), React.createElement("span", {
                                      className: "icon is-small is-left"
                                    }, React.createElement("i", {
                                          "aria-hidden": true,
                                          className: "fas fa-search"
                                        })))), React.createElement("p", {
                              className: "panel-tabs"
                            }, React.createElement("a", {
                                  className: "is-active"
                                }, "all"), React.createElement("a", undefined, "view"), React.createElement("a", undefined, "nominate"), React.createElement("a", undefined, "register"), React.createElement("a", undefined, "vote")), React.createElement("a", {
                              className: "panel-block is-active"
                            }, React.createElement("span", {
                                  className: "panel-icon"
                                }, React.createElement("i", {
                                      "aria-hidden": true,
                                      className: "fas fa-book"
                                    })), "bulma"), React.createElement("a", {
                              className: "panel-block"
                            }, React.createElement("span", {
                                  className: "panel-icon"
                                }, React.createElement("i", {
                                      "aria-hidden": true,
                                      className: "fas fa-book"
                                    })), "marksheet"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
