// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BallotBar");

function str(str_) {
  return str_;
}

var candidateCard = React.createElement("div", {
      className: "card"
    }, React.createElement("div", {
          className: "card-content"
        }, React.createElement("div", {
              className: "media"
            }, React.createElement("div", {
                  className: "media-left"
                }, React.createElement("figure", {
                      className: "image is-48x48"
                    }, React.createElement("img", {
                          alt: "Placeholder image",
                          src: "https://picturepan2.github.io/spectre/img/avatar-2.png"
                        }))), React.createElement("div", {
                  className: "media-content"
                }, React.createElement("p", {
                      className: "title is-4"
                    }, "John Smith"), React.createElement("p", {
                      className: "subtitle is-6"
                    }, "@johnsmith")))), React.createElement("footer", {
          className: "card-footer"
        }, React.createElement("a", {
              className: "card-footer-item",
              href: "#"
            }, "Vote"), React.createElement("a", {
              className: "card-footer-item",
              href: "#"
            }, "Document")));

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "columns is-multiline"
                        }, React.createElement("div", {
                              className: "column is-half"
                            }, candidateCard), React.createElement("div", {
                              className: "column is-half"
                            }, candidateCard), React.createElement("div", {
                              className: "column is-half"
                            }, candidateCard), React.createElement("div", {
                              className: "column is-half"
                            }, candidateCard));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.candidateCard = candidateCard;
exports.make = make;
/* component Not a pure module */
