// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("ContentHeading");

function str(str_) {
  return str_;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("footer", {
                          className: "footer"
                        }, React.createElement("div", {
                              className: "content has-text-centered"
                            }, React.createElement("p", undefined, React.createElement("strong", undefined, "Bulma"), "by", React.createElement("a", {
                                      href: "https://jgthms.com"
                                    }, "Jeremy Thomas"), ". The source code is licensed", React.createElement("a", {
                                      href: "http://opensource.org/licenses/mit-license.php"
                                    }, "MIT"), ". The website content is licensed", React.createElement("a", {
                                      href: "http://creativecommons.org/licenses/by-nc-sa/4.0/"
                                    }, "CC BY NC SA 4.0"), ".")));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
