// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Nav");

function str(str_) {
  return str_;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          className: "navbar is-spaced is-black"
                        }, React.createElement("div", {
                              className: "container"
                            }, React.createElement("div", {
                                  className: "navbar-brand"
                                }, React.createElement("a", {
                                      className: "navbar-item has-text-light logo",
                                      href: "#"
                                    }, React.createElement("b", undefined, "PEN"), React.createElement("span", undefined, "BALLOT")), React.createElement("div", {
                                      className: "navbar-burger burger"
                                    }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                                  className: "navbar-menu"
                                }, React.createElement("div", {
                                      className: "navbar-end"
                                    }, React.createElement("a", {
                                          className: "navbar-item",
                                          href: "/documentation"
                                        }, React.createElement("span", undefined, "Documentation")), React.createElement("a", {
                                          className: "navbar-item",
                                          href: "https://bulma.io/blog/"
                                        }, React.createElement("span", undefined, "Blog")), React.createElement("a", {
                                          className: "navbar-item",
                                          href: "https://bulma.io/expo/"
                                        }, React.createElement("span", undefined, "Expo")), React.createElement("div", {
                                          className: "navbar-item has-dropdown is-hoverable"
                                        }, React.createElement("a", {
                                              className: "navbar-link",
                                              href: "https://bulma.io/more"
                                            }, "More"), React.createElement("div", {
                                              className: "navbar-dropdown",
                                              id: "moreDropdown"
                                            }, React.createElement("a", {
                                                  className: "navbar-item ",
                                                  href: "https://bulma.io//bulma-start"
                                                }, React.createElement("span", undefined, React.createElement("strong", undefined, "Bulma start"), React.createElement("br", undefined), "A tiny npm package to get started")), React.createElement("hr", {
                                                  className: "navbar-divider"
                                                }), React.createElement("a", {
                                                  className: "navbar-item ",
                                                  href: "https://bulma.io//made-with-bulma"
                                                }, React.createElement("span", undefined, React.createElement("strong", undefined, "Made with Bulma"), React.createElement("br", undefined), "The official community badge")))), React.createElement("a", {
                                          className: "navbar-item",
                                          href: "https://github.com/jgthms/bulma",
                                          target: "_blank"
                                        }, React.createElement("span", {
                                              className: "icon"
                                            }, React.createElement("i", {
                                                  className: "fab fa-lg fa-github-alt"
                                                }))), React.createElement("a", {
                                          className: "navbar-item",
                                          href: "https://twitter.com/jgthms",
                                          target: "_blank"
                                        }, React.createElement("span", {
                                              className: "icon"
                                            }, React.createElement("i", {
                                                  className: "fab fa-lg fa-twitter"
                                                }))), React.createElement("div", {
                                          className: "navbar-item"
                                        }, React.createElement("a", {
                                              className: "button is-danger is-outlined"
                                            }, "Login"))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
