// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CandidateList$ReactTemplate = require("./CandidateList.bs.js");

var component = ReasonReact.statelessComponent("PhaseView");

function str(str_) {
  return str_;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("article", {
                              className: "message is-info"
                            }, React.createElement("div", {
                                  className: "message-header"
                                }, React.createElement("p", undefined, "VIEW")), React.createElement("div", {
                                  className: "message-body"
                                }, "This ballot is in view phase.", React.createElement("br", undefined), "If you think there is a problem with the current phase please inform any of the", React.createElement("b", undefined, " admins"), " or the", React.createElement("b", undefined, " moderators"), ".", React.createElement("br", undefined), " For more information regarding phases please refer to the ", React.createElement("a", undefined, "documentation"), ".")), ReasonReact.element(/* None */0, /* None */0, CandidateList$ReactTemplate.make(/* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.make = make;
/* component Not a pure module */
