// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("SideBar");

function divider(dataContent) {
  return React.cloneElement(React.createElement("li", {
                  className: "divider"
                }), {
              "data-content": dataContent
            });
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "side-bar"
                        }, React.createElement("div", {
                              className: "columns"
                            }, React.createElement("div", {
                                  className: "column col-8"
                                }, React.createElement("div", {
                                      className: "logo rounded"
                                    }, React.createElement("span", {
                                          className: "text-bold"
                                        }, "PEN"), "BALLOT")), React.createElement("div", {
                                  className: "column col-4"
                                }, React.createElement("button", {
                                      className: "btn btn-block"
                                    }, "Bye?"))), React.createElement("ul", {
                              className: "nav"
                            }, divider("ADITHYA KUMAR"), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Profile")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Nominations")), divider("SOCKET"), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Online Help")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.cloneElement(React.createElement("a", {
                                          className: "badge"
                                        }), {
                                      "data-badge": 6
                                    }, "Announcements")), divider("DEV"), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Documentation")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Github")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Contributers")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Guidelines")), divider("LEGAL"), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      href: "#"
                                    }, "Terms of usage"))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.divider = divider;
exports.make = make;
/* component Not a pure module */
