// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("UserCard");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "user-card"
                        }, React.createElement("div", {
                              className: "display-picture"
                            }, React.createElement("figure", {
                                  className: "avatar avatar-xl"
                                }, React.createElement("img", {
                                      alt: "Adithya Kumar",
                                      src: "https://picturepan2.github.io/spectre/img/avatar-2.png"
                                    }))), React.createElement("div", {
                              className: "card"
                            }, React.createElement("div", {
                                  className: "card-header"
                                }, React.createElement("div", {
                                      className: "card-title h6"
                                    }, "Adithya Kumar"), React.createElement("div", {
                                      className: "card-subtitle text-gray"
                                    }, "111501017@smail.iitpkd.ac.in")), React.createElement("div", {
                                  className: "card-footer"
                                }, React.createElement("button", {
                                      className: "btn btn-primary"
                                    }, "Vote"), React.createElement("a", {
                                      className: "btn"
                                    }, "Document"))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
