// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

function authUser(axiosConfig) {
  var data = {
    def: 0
  };
  return Axios.post("/ballot/token-service", data, axiosConfig);
}

function $$delete(email, axiosConfig) {
  var data = {
    email: email
  };
  return Axios.post("/ballot/delete", data, axiosConfig);
}

function updatePersonal(email, name, picture, axiosConfig) {
  var data = {
    email: email,
    name: name,
    picture: picture
  };
  return Axios.post("/ballot/update-personal", data, axiosConfig);
}

function updateRole(email, roleCode, axiosConfig) {
  var data = {
    email: email,
    role_code: roleCode
  };
  return Axios.post("/ballot/update-role", data, axiosConfig);
}

exports.authUser = authUser;
exports.$$delete = $$delete;
exports.updatePersonal = updatePersonal;
exports.updateRole = updateRole;
/* axios Not a pure module */
